version: '3'
services:
  magicmirror:
    container_name: magicmirror
    build: .
    restart: unless-stopped
    environment:
      - TZ='America/Los_Angeles'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/opt/magic_mirror/config
      - ./modules:/opt/magic_mirror/modules
    ports:
      - 8080:8080
